baseURL: "https://kinpokoblog.com/"
languageCode: ja-jp
title: kinpoko BLOG
theme: mini
publishDir: docs
canonifyurls: true


hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

googleAnalytics: your-google-analytics-id
disqusShortname: your-disqus-shortname

# Hugo Configure Markup
# see: https://gohugo.io/getting-started/configuration-markup#highlight
markup:
  highlight:
    guessSyntax: true
    style: emacs


# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  # e.g.
  github: https://github.com/kinpoko
  twitter: https://twitter.com/aaaabbbbbbcc
  # facebook: your-facebook-link


# Site parameters
params:
  # Site Author
  author: Author
  # Author biography
  bio: 愛していると云ってくれ
  # Site Description, used in HTML meat
  description: kinpokoのブログ
  enableRSS: true
  # To enable comments, you may need to set `disqusShortname`
  enableComments: false
  # To enable comments, you may need to set `googleAnalytics`
  enableGoogleAnalytics: false

  # Optional
  home: '' # Default: Home
  about: '' # Default: About
  archive: '' # Default: Archive
  tags: '' # Default: Tags
  subscribe: 'RSS' # Default: Subscribe
  olderPosts: '' # Default: Older Posts
  newerPosts: '' # Default: Newer Posts
  copyright: '© 2021 kinpoko' # Default: © Copyright 2021 ❤️ author
  title404: '' # Default: 404 - Page Not Found
  subtitle404: '' # Default: The content you're looking for doesn't seem to exist.
  readMore: '' # Default: Read More

  # Extra links in navigation
  links:
    # e.g.
    # - name: Project
    #   path: /project
